FROM node:18-slim

WORKDIR /app

# Install curl for health checks
RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

COPY /server/package*.json ./
RUN npm install

COPY server ./server

ENV PORT=8001

EXPOSE 8001

# Add a startup script to wait for MySQL
CMD ["node", "server/server.js"]
