services:
  client:
    container_name: coursecritic-client
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "8080:80"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  server:
    container_name: coursecritic-server
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT:-3306}
      - NODE_ENV=production
      - API_URL=${REACT_APP_API_URL}
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/api/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s
    restart: unless-stopped

networks:
  app-network:
    name: coursecritic_network



