services:
  client:
    container_name: coursecritic-client
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "8080:80"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - VITE_API_URL=${VITE_API_URL}
      - REACT_APP_API_URL: "${REACT_APP_API_URL}"
    env_file:
      - .env

  server:
    container_name: coursecritic-server
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT:-3306}
      - NODE_ENV=production
      - PORT=8001
      - DB_HOST: "${DB_HOST}"
      - DB_USER: "${DB_USER}"
      - DB_PASSWORD: "${DB_PASSWORD}"
      - DB_NAME: "${DB_NAME}"
      - DB_PORT: "${DB_PORT:-3306}"
      - NODE_ENV: production
      - PORT: 8001
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  app-network:
    name: coursecritic_network



