FROM node:18-alpine

WORKDIR /app

COPY /client/package*.json ./
RUN npm install

# Add vite if not in package.json
RUN npm install -D vite @vitejs/plugin-react

COPY client/ ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
