services:
  client:
    container_name: coursecritic-client-dev
    build:
      context: .
      dockerfile: Dockerfile.react.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8001
    networks:
      - app-network

  server:
    container_name: coursecritic-server-dev
    build:
      context: .
      dockerfile: Dockerfile.node.dev
    ports:
      - "8001:8001"
    volumes:
      - ./server:/app/server
      - /app/node_modules
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT:-3306}
      - NODE_ENV=development
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app-network:
    name: coursecritic_network_dev
