services:
  client:
    container_name: coursecritic-client
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "8080:80"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=

  server:
    container_name: coursecritic-server
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=157.230.188.42
      - DB_USER=admin
      - DB_PASSWORD=admin_password
      - DB_NAME=coursecritic
      - DB_PORT=3306
      - NODE_ENV=production
      - PORT=8001
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  app-network:
    name: coursecritic_network



