FROM node:18-slim

WORKDIR /app

# Install wget for health checks
RUN apt-get update && \
    apt-get install -y wget && \
    rm -rf /var/lib/apt/lists/*

COPY server/package*.json ./
RUN npm install

COPY server ./server

ENV PORT=8001

EXPOSE 8001

CMD ["node", "server/server.js"]
